### ISSUE TITLE
Search filter on assets dropdown

### ISSUE THREAD

**Issue by janzheng** [pmaji/crypto-asset-comparison-tool#14]
Would be cool if you could type and the asset list would update as you type! It's not even listed alphabetically and you can't just type in anything, so changing assets is very difficult right now.

Thanks!

**Comment by pmaji** [comment]
Hey @janzheng ! Thanks for the feedback. I'm not sure what you mean though, as that's exactly what it's built to do presently. The code behind the search bar is a selectize function, so as you type, it autofilters the list. I have attached an image below. If you could clarify beyond this then I would appreciate, because presently I don't see how what you are suggesting isn't already possible.

![screen shot 2018-05-08 at 9 34 39 am](https://user-images.githubusercontent.com/25461122/39760419-3ddd33f4-52a3-11e8-9e10-3689108a8338.JPG)

**Comment by janzheng** [comment]
hmmm ok I think I got it! Seems like you have to hit backspace/delete to clear the text already there before you can input any new text; I was just trying to type more text or select-all and typing more text, both which doesn't work. 

Also, when you search for a symbol that doesn't exist (e.g. "SPY"), it'll revert back to the previous name, without showing a dropdown option that says something like " 'SPY' not found"

BUT this is an amazing tool, and thanks for sharing!

**Comment by pmaji** [comment]
That's a good point @janzheng. It's a little tough to explain, but essentially this method is a bit faster by about a second than what I think I could build that would handle entries that aren't available (like your SPY example) by producing an error / "not found" message. That said, I'll look over the option locally, and see if I could potentially speed it up. If not, I'll keep the present structure :) Closing the issue now because I view this as taken care of broadly speaking.
