### ISSUE TITLE
GUI/webpage @ IP address not responsive

### ISSUE THREAD

**Issue by Gilray4** [pmaji/crypto-asset-comparison-tool#15]
Paul:
 When I try to access the "financial-asset-comparison-tool"
@ - "http://96.241.22.80:7597/"
or- "https://pjeff.shinyapps.io/crypto-asset-comparison-tool/"

 The page loads fine. Almost immediately though the page 'grays' (actually blue's) over and is unfunctional ?
Am I missing something? I have read the white paper (twice) and still can't figure out how to use the app due to it graying out.

 I am running Ubuntu 16 something LTS with Firefox browser.

**Comment by pmaji** [comment]
Appreciate your calling that out @Gilray4 --it is not a problem with the code itself, but a problem with an update made to one of the APIs it relies on for its data feed. I'll look into trying to fix this in the near future.

**Comment by pmaji** [comment]
@Gilray4 -- just wanted to update you. After many hours of tearing apart the code from scratch, I found what is causing the error. One of our APIs has messed up in the way they do type conversions. Essentially they updated their tables and one of their "price" columns went from a numeric type column to a character type column. I will build out a fix to handle for this and will have the app up live shortly.

**Comment by pmaji** [comment]
@Gilray4 -- I have patched it such that the version hosted at [this link here](https://pjeff.shinyapps.io/crypto-asset-comparison-tool/) is now working perfectly well. I would request, however, that you check back over the next few days because by then I will have updated the version hosted at http://96.241.22.80:7597/ . This is important because using the version on shinyapps.io costs me a great deal more than the version hosted at 96.241... etc. etc. , and we haven't raised nearly enough in donations to make hosting on shinyapps.io sustainable over the long term. 

Thanks again for bringing this to my attention, and hope you enjoy the app / continue to support it! 
(closing this issue now)

**Comment by Gilray4** [comment]
Paul
Thank you for your time and consideration.
I really like the work you have done !

I am curious, if you feel free to discuss/divulge...
What is the band width consumption (now and projected)
That your apps require ?
I possibly could be of help in donating some disk space/bandwidth ?

**Comment by pmaji** [comment]
@Gilray4 thanks so much for the offer! The version hosted at "http://96.241.22.80:7597/" is actually pretty light to host--it just takes a little longer to update because we do it manually. The other link is one hosted by ShinyApps.io that costs a lot more to maintain, so while I keep it on there so that folks like you can have access to the app even when the main link is down / out of date, it's not my preference that people use the ShinyApps.io link often, given the price.

As for disk space/bandwidth, it's pretty minimal, but varies computer to computer. Try forking it, running the code locally, and just look at your disk utilization / whatever disk utility you have to see how big of an impact hosting it would have in terms of %--it shouldn't be much. If after that you would be interested in helping to host it, that would be great! I would just caution that unless you know how to host the app publicly, the start-up cost to learn might not be worth it, which is generally speaking why we are content for now with the status quo, and seeking donations for long term sustainability.
