### ISSUE TITLE
Warning: Error in bmerge: Incompatible join types: x.date (character) and i.date (integer)

### ISSUE THREAD

**Issue by matthanc** [pmaji/crypto-asset-comparison-tool#17]
Hey Paul,

Thanks for putting this together. I'm trying to give it a go and play around with it but get the subject/below errors. I've played around with the function script a bit but can't seem to find a fix. Any info on how to get it to run would be greatly appreciated!

`Warning: Error in bmerge: Incompatible join types: x.date (character) and i.date (integer)
  [No stack trace available]
Warning: Error in bmerge: Incompatible join types: x.date (character) and i.date (integer)
  114: <Anonymous>
Warning: Error in bmerge: Incompatible join types: x.date (character) and i.date (integer)
  102: <Anonymous>
Warning: Error in bmerge: Incompatible join types: x.date (character) and i.date (integer)
  111: <Anonymous>
Warning: Error in bmerge: Incompatible join types: x.date (character) and i.date (integer)
  91: <Anonymous>
Warning: Error in bmerge: Incompatible join types: x.date (character) and i.date (integer)
  118: <Anonymous>
Warning: Error in bmerge: Incompatible join types: x.date (character) and i.date (integer)
  71: <Anonymous>
Warning: Error in bmerge: Incompatible join types: x.date (character) and i.date (integer)
  116: <Anonymous>
Warning: Error in bmerge: Incompatible join types: x.date (character) and i.date (integer)
  114: <Anonymous>
Warning: Error in bmerge: Incompatible join types: x.date (character) and i.date (integer)
  111: <Anonymous>
Warning: Error in bmerge: Incompatible join types: x.date (character) and i.date (integer)
  118: <Anonymous>
Warning: Error in bmerge: Incompatible join types: x.date (character) and i.date (integer)
  116: <Anonymous>`

**Comment by pmaji** [comment]
Hmm... not sure. Can't really tell exactly where the error is coming from but I can confirm the current version still works both locally and as hosted online for me.

My guess (because the function that's failing for you is from data.table) is that you have an older version of data.table than the one I use for the app. I'd recommend starting a new virtual machine / fresh repo, and then installing all of the packages needed for the app in a fresh instance. That's my best guess, and hope that helps!

Admittedly, I bear some responsibility here as well -- I could done some sort of conda-esque/ requirements doc with exact versions of each package used, but this was one of my first published projects and I hadn't yet gotten around to that level of best practice haha and don't have much time to redo that now. I hope that helps!

**Comment by matthanc** [comment]
No worries! Thanks for the reply and for checking it out! I'll keep playing around with it to see if I can get it to work.
